name: CI Workflow

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: automated_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@preview
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install -vv --no-interaction
        poetry show -vv
    - name: Create database
      run: |
        echo "Check version"
        psql postgres://postgres:postgres@localhost:5432/postgres -c 'SELECT version()'
        echo "Run db creation"
        #
        poetry run python bin/destroy_and_setup_psqlgraph.py --user postgres --password postgres
    - name: Test with pytest
      run: |
        poetry run pytest test/ -vv --cov=src --cov=migrations/versions --cov-report xml
    - name: Submit coverage report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls
